
services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: builder
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nx serve backend
    ports:
      - "${BACKEND_PORT}:3000"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: builder
    environment:
      API_URL: http://localhost:${BACKEND_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GA_MEASUREMENT_ID: ${GA_MEASUREMENT_ID}
    volumes:
      - .:/app
      - /app/node_modules
    command: npx nx serve frontend --host 0.0.0.0
    ports:
      - "${FRONTEND_PORT}:4200"

  nginx:
    profiles: ["prod-only"]
